# Generated by Django 4.2.4 on 2024-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/media/uploads'),
        ),
    ]
